.PHONY:		all

all:
	$(MAKE) -C noice/noice_beeb6309 all
	$(MAKE) -C beeb6809-mos all
	$(MAKE) -C beebMOSloader-noice all
	
clean:
	$(MAKE) -C noice/noice_beeb6309 clean
	$(MAKE) -C beeb6809-mos clean
	$(MAKE) -C beebMOSloader-noice clean
	