	* VERIFY
	*
	* VERIFY LAST SECTOR WRITTEN
VERIFY		LDA	#RDCMND				; SETUP VERIFY COMMAND
	IF DRIVERS_FLEX
		TST	PRCNT				; ARE WE SPOOLING?
		BEQ	VERIF2				; SKIP IF NOT
		SWI3					;  CHANGE TASKS IF SO
		NOP					;  NECESSARY FOR SBUG
	ENDIF
VERIF2		ORCC	#$50				;  DISABLE INTERRUPTS
		STA	COMREG				; ISSUE VERIFY COMMAND
		LBSR	DEL32U				; GO DELAY
		LBSR	WAIT				; WAIT TIL WD IS DONE
		ANDCC	#$AF				;  ENABLE INTERRUPTS
		ANDB	#VERMSK				; MASK ERRORS
		RTS					;  RETURN
