	* WAIT
	*
	* WAIT FOR 1771 TO FINISH COMMAND
WAIT		
	IF DRIVERS_FLEX
		TST	PRCNT				; ARE WE SPOOLING?
		BEQ	WAIT1				; SKIP IF NOT
		SWI3					;  SWITCH TASKS IF SO
		NOP					;  NECESSARY FOR SBUG
	ENDIF
WAIT1		LDB	COMREG				; GET WD STATUS
		BITB	#BUSY				; CHECK IF BUSY
		BNE	WAIT				; LOOP TIL NOT BUSY
		; DB catchall - if DRQ active read data
		BITB	#DRQ
		BEQ	1F
		TST	DATREG		
1
		JSR	DEL32U
		TST	COMREG				; second bite

		BITB	#BUSY

		RTS					;  RETURN
