	* CHKRDY
	*
	* CHECK DRIVE READY ROUTINE
CHKRDY		LDA	3,X				; GET DRIVE NUMBER
		CMPA	#1				; BE SURE IT'S 0 OR 1
		BLS	OK				; BRANCH IF OK
		LDB	#$80				; ELSE, SHOW NOT READY
		ORCC	#$01				; SEC
		RTS					; RETURN
OK		CLRB					;  SHOW NO ERROR
		ANDCC	#$FE				; CLC
		RTS
	* FIND THE TRACK FOR CURRENT DRIVE
FNDTRK		LDX	#DRVTRK				; POINT TO TRACK STORE
		LDB	CURDRV				; GET CURRENT DRIVE
		ABX					;  POINT TO DRIVE'S TRACK
		RTS					;  RETURN
