	* REST
	*
	* REST RESTORES THE HEAD TO 00
REST		PSHS	X				; SAVE X REGISTER
		BSR	DRV				; DO SELECT
		ORCC	#$50
		LDA	#RSCMND				; SETUP RESTORE COMMAND
		STA	COMREG				; ISSUE RESTORE COMMAND
		BSR	DEL32U				; DELAY
		LBSR	WAIT				; WAIT TIL WD IS FINISHED
		PULS	X				; RESTORE POINTER
		BITB	#$58				; CHECK FOR ERROR	- DB was D8!
		ANDCC	#$AF
		RTS					;  RETURN
