	* DRV
	*
	* SELECT THE SPECIFIED DRIVE
DRV		LDA	3,X				; GET DRIVE NUMBER
		CMPA	#1				; ENSURE IT'S < 4
		BLS	DRV2				; BRANCH IF OK
		LDB	#$0F				; ELSE SET ERROR VALUE
		ORCC	#$01				; SEC
		RTS
DRV2		BSR	FNDTRK				; FIND TRACK
		LDB	TRKREG				; GET CURRENT TRACK
		STB	0,X				; SAVE IT
		JSR	SETDRVREG			; SET NEW DRIVE
		STA	CURDRV
		BSR	FNDTRK				; FIND NEW TRACK
		LDA	0,X
		STA	TRKREG				; PUT NEW TRACK IN WD
		BSR	DEL32U				; DELAY
		BRA	OK
		* A=  DRV, Cy is Set for SIDE=0, Clear for SIDE=1
SETDRVREG	PSHS	A,CC
		RORA
		LDA	#%00101001			; drive 0, DDEN=1, MR=1		
		ADCA	#0
		PULS	CC
		BCS	1F
		ORA	#%00000100			; side
1		STA	DRVREG
		PULS	A,PC
