* DB: modified to use the minimos 


	* CONSOLE I/O DRIVER PACKAGE
	*
	* COPYRIGHT (C) 1980 BY
	* TECHNICAL SYSTEMS CONSULTANTS, INC.
	* 111 PROVIDENCE RD, CHAPEL HILL, NC 27514
	*
	* CONTAINS ALL TERMINAL I/O DRIVERS AND INTERRUPT HANDLING
	* INFORMATION. THIS VERSION IS FOR A SWTPC SYSTEM USING
	* A SBUG MONITOR AND THE MF-68 MINIFLOPPY SYSTEM. THE
	* INTERRUPT TIMER ROUTINES ARE FOR A SWTPC MP-T TIMER
	* CARD ADDRESSED AT $E012.
	* SYSTEM EQUATES

OSRDCH		EQU	$FFE0
OSPEEKCH	EQU	$FFDD
OSWRCH		EQU	$FFEE

mos_vars	EQU	$E500
IRQ1V		EQU	mos_vars + 0
SWI3V		EQU	mos_vars + 2

CHPR		EQU	$C700				; CHANGE PROCESS ROUTINE
	***************************************************
	* *
	* I/O ROUTINE VECTOR TABLE *
	* *
		ORG	$D3E5				; TABLE STARTS AT $D3E5 *
	* *
INCHNE		FDB	OSRDCH				; INPUT CHAR - NO ECHO *
IHNDLR		FDB	IHND				; IRQ INTERRUPT HANDLER *
SWIVEC		FDB	SWI3V				; SWI3 VECTOR LOCATION *
IRQVEC		FDB	IRQ1V				; IRQ VECTOR LOCATION *
TMOFF		FDB	TOFF				; TIMER OFF ROUTINE *
TMON		FDB	TON				; TIMER ON ROUTINE *
TMINT		FDB	TINT				; TIMER INITIALIZE ROUTINE *
MONITR		FDB	ENTERMON			; MONITOR RETURN ADDRESS *
TINIT		FDB	INIT				; TERMINAL INITIALIZATION *
STAT		FDB	OSPEEKCH			; CHECK TERMINAL STATUS *
OUTCH		FDB	OSWRCH				; TERMINAL CHAR OUTPUT *
INCH		FDB	INPUT				; TERMINAL CHAR INPUT *
	* *
	***************************************************
	* ACTUAL ROUTINES START HERE
	******************************
		ORG	$D370

ENTERMON	SWI					; invoke monitor
	* TERMINAL INITIALIZE ROUTINE
INIT		RTS
	* TERMINAL INPUT CHAR. ROUTINE - W/ ECHO
INPUT		JSR	OSRDCH
	* TERMINAL OUTPUT CHARACTER ROUTINE
OUTPUT		JMP	OSWRCH
	* TIMER INITIALIZE ROUTINE
TINT		RTS
	* TIMER ON ROUTINE
TON		RTS
	* TIMER OFF ROUTINE
TOFF		RTS
	* IRQ INTERRUPT HANDLER ROUTINE
IHND		RTI
	* END STATEMENT HAS FLEX TRANSFER ADDRESS!
		END	$CD00