	*
	* DRIVER INITIALIZATION
INIT		LDX	#CURDRV				; POINT TO VARIABLES
		LDB	#5				; NO. OF BYTES TO CLEAR
INIT2		CLR	,X+				; CLEAR THE STORAGE
		DECB
		BNE	INIT2				; LOOP TIL DONE
WARM		RTS					;  WARM START NOT NEEDED
